"""7 Wonders Duel rules engine and AI project."""

from .bots import (
    GreedyBot,
    MilitaryAggressiveBot,
    MilitaryEconomyBot,
    RandomBot,
    ScienceAggressiveBot,
    ScienceEconomyBot,
    play_game,
    play_series,
)
from .buffer import (
    GameRecord,
    GameRecorder,
    MoveRecord,
    ReplayMismatchError,
    append_records,
    from_json_line,
    read_records,
    replay,
    to_json_line,
)
from .codec import (
    NUM_ACTIONS,
    decode_action,
    encode_action,
    legal_action_indices,
    legal_action_mask,
)
from .data import BackType, back_type_of
from .encoder import ENCODER_SIGNATURE, Encoding, Token, TokenType, encode
from .engine import (
    Action,
    ActionUse,
    apply_action,
    legal_actions,
    resolve_pending_choice,
    score_player,
    start_next_age,
)
from .game import (
    ChanceKind,
    GameState,
    HiddenInformationError,
    ResolvedChance,
    StepResult,
    VictoryType,
    new_game,
)
from .pool import (
    UnseenPool,
    enumerate_card_reveal,
    enumerate_great_library,
    enumerate_wonder_flip,
    resample_hidden,
    unseen_pool,
)

__all__ = [
    "Action",
    "ActionUse",
    "BackType",
    "ChanceKind",
    "ENCODER_SIGNATURE",
    "Encoding",
    "GameRecord",
    "GameRecorder",
    "GameState",
    "GreedyBot",
    "HiddenInformationError",
    "MoveRecord",
    "MilitaryAggressiveBot",
    "MilitaryEconomyBot",
    "NUM_ACTIONS",
    "RandomBot",
    "ReplayMismatchError",
    "ResolvedChance",
    "ScienceAggressiveBot",
    "ScienceEconomyBot",
    "StepResult",
    "Token",
    "TokenType",
    "UnseenPool",
    "VictoryType",
    "append_records",
    "apply_action",
    "back_type_of",
    "decode_action",
    "encode",
    "encode_action",
    "from_json_line",
    "legal_action_indices",
    "legal_action_mask",
    "enumerate_card_reveal",
    "enumerate_great_library",
    "enumerate_wonder_flip",
    "legal_actions",
    "new_game",
    "play_game",
    "play_series",
    "read_records",
    "replay",
    "resample_hidden",
    "resolve_pending_choice",
    "to_json_line",
    "score_player",
    "start_next_age",
    "unseen_pool",
]
