"""Stage-1 offline A/B: can the network USE exact positional control?

The cheap arm of the W3 experiment, and the one that can kill it before any
rental. Every arm starts from the same checkpoint, trains the same number of
steps on the same examples with the same split, and differs only in what the
model is shown or asked to predict:

    baseline   control inputs OFF, no auxiliary head
    inputs     control inputs ON
    aux        control inputs OFF, auxiliary control head ON
    both       control inputs ON, auxiliary control head ON
    shuffled   control inputs ON, but the control CHANNELS ARE PERMUTED across
               positions -- the causal control. If it gains as much as
               `inputs`, the gain was not the information.

What this measures, and what it does not. The buffers were generated by a policy
that never saw control features, so this asks whether control helps predict
EXISTING search targets -- not whether a policy that can see control plays
better. A positive result is strong evidence to proceed to an arena; a flat
result does not rule out a benefit in self-play.

Arms are compared to `baseline`, never to the incumbent: the incumbent has not
had this training run, so comparing to it would conflate the effect of control
with the effect of more training.

    python -m games.seven_wonders_duel.w3_offline_ab \\
        --checkpoint extension_7wd/candidate_0085.pt \\
        --buffers "<cloud2>/buffers" --games 4000 --steps 400 \\
        --arms baseline,inputs,aux,shuffled --seeds 3 --device cuda
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import random
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

#: (control inputs on, auxiliary head on, shuffle the control channels)
ARMS = {
    "baseline": (False, False, False),
    "inputs": (True, False, False),
    "aux": (False, True, False),
    "both": (True, True, False),
    "shuffled": (True, False, True),
}


def load_examples(buffers: Path, games: int, log) -> list:
    """Replay recorded games into Examples, through the verified replay path."""

    from .buffer import read_records
    from .dataset import examples_from_records

    records = []
    for path in sorted(buffers.glob("iter_*.jsonl")):
        records.extend(read_records(path))
        if len(records) >= games:
            records = records[:games]
            break
    examples = examples_from_records(records)
    log(f"  {len(records)} games -> {len(examples)} examples")
    return examples


def game_honest_split(examples, holdout: float, seed: int):
    """Split by GAME, never by position.

    Every position in a game carries the same outcome label, so a position-level
    split lets a model score on validation by recognising a game it trained on.
    """

    keys = sorted({int(e.game_key) for e in examples})
    rng = random.Random(seed)
    rng.shuffle(keys)
    held = set(keys[: max(1, int(len(keys) * holdout))])
    train = [e for e in examples if int(e.game_key) not in held]
    val = [e for e in examples if int(e.game_key) in held]
    return train, val


def shuffle_control_features(examples, seed: int, log) -> list:
    """Permute the control CHANNELS across positions. The causal control.

    Operates on the encoded features, not on the auxiliary labels: the inputs
    arm bakes control into the tokens at encode time, so shuffling the labels
    would leave the treatment untouched and quietly report the control as a copy
    of it.

    Preserves every marginal -- same values, same distribution, same count of
    nonzeros -- and destroys only the correspondence between a position and its
    control map. Positions are permuted within groups of equal tableau-token
    count, so the swap stays shape-valid.
    """

    import numpy as np

    from .dataset import TYPE_IDS
    from .encoder import (
        CONTROL_FEATURES,
        GLOBAL_FEATURES,
        TABLEAU_FEATURES,
        TokenType,
    )

    valid = GLOBAL_FEATURES.index("control_valid")
    first = TABLEAU_FEATURES.index(CONTROL_FEATURES[0])
    stop = first + len(CONTROL_FEATURES)
    global_id = TYPE_IDS[TokenType.GLOBAL]
    tableau_id = TYPE_IDS[TokenType.TABLEAU]

    rows, groups = [], {}
    for index, example in enumerate(examples):
        types = np.asarray(example.type_ids)
        tableau = np.flatnonzero(types == tableau_id)
        rows.append((types, tableau))
        groups.setdefault(len(tableau), []).append(index)

    rng = random.Random(seed)
    donors = {}
    for members in groups.values():
        shuffled = members[:]
        rng.shuffle(shuffled)
        donors.update(dict(zip(members, shuffled)))

    out, swapped = [], 0
    for index, example in enumerate(examples):
        donor = donors[index]
        if donor == index:
            out.append(example)
            continue
        features = np.array(example.features, dtype=np.float32, copy=True)
        source = np.asarray(examples[donor].features, dtype=np.float32)
        mine_types, mine_tab = rows[index]
        their_types, their_tab = rows[donor]
        for a, b in zip(mine_tab, their_tab):
            features[a, first:stop] = source[b, first:stop]
        gm = np.flatnonzero(mine_types == global_id)
        gt = np.flatnonzero(their_types == global_id)
        if len(gm) and len(gt):
            features[gm[0], valid] = source[gt[0], valid]
        out.append(
            dataclasses.replace(
                example, features=features.astype(example.features.dtype)
            )
        )
        swapped += 1
    log(f"  shuffled control on {swapped}/{len(examples)} positions "
        f"({len(groups)} token-count groups)")
    return out


def run_arm(name, args, examples, log) -> dict:
    """Train one arm from the frozen checkpoint, score it on held-out games."""

    import torch

    from .encoder import set_control_features
    from .train import (
        evaluate,
        load_checkpoint,
        make_checkpoint,
        model_from_config,
        train_steps,
    )

    inputs_on, aux_on, shuffled = ARMS[name]
    set_control_features(inputs_on)
    if shuffled:
        examples = shuffle_control_features(examples, args.split_seed, log)

    checkpoint = torch.load(args.checkpoint, map_location="cpu", weights_only=False)
    config = dict(checkpoint["config"])
    config["control_head"] = aux_on
    model = model_from_config(config)
    load_checkpoint(args.checkpoint, model, migrate=True, checkpoint=checkpoint)

    train_examples, val_examples = game_honest_split(
        examples, args.holdout, args.split_seed
    )
    log(f"  {len(train_examples)} train / {len(val_examples)} val")

    torch.manual_seed(args.seed)
    started = time.perf_counter()
    train_steps(
        model,
        train_examples,
        val_examples,
        device=args.device,
        steps=args.steps,
        batch_size=args.batch_size,
        lr=args.lr,
        seed=args.seed,
        precision=args.precision,
        validate_every=max(1, args.steps),
        log=lambda m: log(f"    {m}"),
    )
    elapsed = time.perf_counter() - started
    metrics = evaluate(
        model, val_examples, device=args.device, batch_size=args.batch_size
    )

    if args.save_dir:
        out_dir = Path(args.save_dir)
        if not out_dir.is_absolute():
            out_dir = REPO_ROOT / out_dir
        out_dir.mkdir(parents=True, exist_ok=True)
        # Saved so the CORPUS measurement can follow: aggregate policy top-1
        # moves slowly, and a narrow blind-spot fix can hide inside it.
        torch.save(
            make_checkpoint(model, config), out_dir / f"{name}_seed{args.seed}.pt"
        )

    return {
        "arm": name,
        "seed": args.seed,
        "control_inputs": inputs_on,
        "control_head": aux_on,
        "shuffled": shuffled,
        "minutes": round(elapsed / 60, 2),
        "val": {
            k: (round(v, 5) if isinstance(v, float) else v)
            for k, v in metrics.items()
        },
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--checkpoint", required=True)
    parser.add_argument("--buffers", required=True)
    parser.add_argument("--arms", default="baseline,inputs,aux,shuffled")
    parser.add_argument("--games", type=int, default=4000)
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--lr", type=float, default=5e-5)
    parser.add_argument("--holdout", type=float, default=0.15)
    parser.add_argument("--seed", type=int, default=20260904)
    parser.add_argument("--seeds", type=int, default=1,
                        help="training seeds per arm. One seed cannot resolve a "
                             "3-5 point effect, the size this project's gates "
                             "actually see.")
    parser.add_argument("--split-seed", type=int, default=7,
                        help="held FIXED across arms and seeds: arms must share "
                             "a split, or the comparison is between splits")
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--precision", default="fp32")
    parser.add_argument("--save-dir",
                        default="runs/seven_wonders_duel/w3_offline_ab")
    parser.add_argument("--out",
                        default="runs/seven_wonders_duel/w3_offline_ab.json")
    args = parser.parse_args(argv)

    def log(message):
        print(message, flush=True)

    arms = [a.strip() for a in args.arms.split(",") if a.strip()]
    unknown = [a for a in arms if a not in ARMS]
    if unknown:
        raise SystemExit(f"unknown arms {unknown}; known: {sorted(ARMS)}")

    from .encoder import set_control_features

    # Derived ONCE per input setting and shared across arms and seeds. Control
    # values are baked into tokens at encode time, so only the two encodings
    # differ; re-deriving per arm was 73% of the run for nothing.
    cache = {}
    results = []
    base_seed = args.seed
    for index in range(args.seeds):
        args.seed = base_seed + index
        log("")
        log(f"#### seed {args.seed} ({index + 1}/{args.seeds}) ####")
        for name in arms:
            log("")
            log(f"=== {name} (seed {args.seed}) ===")
            inputs_on = ARMS[name][0]
            if inputs_on not in cache:
                set_control_features(inputs_on)
                cache[inputs_on] = load_examples(Path(args.buffers), args.games, log)
            set_control_features(inputs_on)
            row = run_arm(name, args, list(cache[inputs_on]), log)
            results.append(row)
            log(f"  -> {json.dumps(row['val'])}")
    args.seed = base_seed
    set_control_features(True)

    report = {
        "harness": "w3_offline_ab",
        "checkpoint": str(args.checkpoint),
        "buffers": str(args.buffers),
        "games": args.games,
        "steps": args.steps,
        "batch_size": args.batch_size,
        "lr": args.lr,
        "seed": base_seed,
        "seeds": args.seeds,
        "split_seed": args.split_seed,
        "arms": results,
        "note": (
            "Buffers came from a policy that never saw control features, so "
            "this measures prediction of EXISTING search targets, not playing "
            "strength. Compare arms to `baseline`, never to the incumbent."
        ),
    }

    # Paired per seed: each arm is compared against the baseline that saw the
    # SAME seed and split, so training randomness cancels rather than becoming
    # the effect.
    by_seed = {}
    for row in results:
        by_seed.setdefault(row["seed"], {})[row["arm"]] = row["val"]
    deltas = {}
    for at_seed in by_seed.values():
        base = at_seed.get("baseline")
        if not base:
            continue
        for arm, val in at_seed.items():
            if arm == "baseline":
                continue
            for metric in ("policy_top1", "value_acc", "total"):
                deltas.setdefault((arm, metric), []).append(
                    val.get(metric, 0) - base.get(metric, 0)
                )
    if deltas:
        report["paired_deltas"] = {
            f"{arm}:{metric}": {"values": v, "mean": sum(v) / len(v)}
            for (arm, metric), v in deltas.items()
        }

    out = Path(args.out)
    if not out.is_absolute():
        out = REPO_ROOT / out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    log("")
    log("=" * 70)
    log(f"{'arm':<10}{'seed':>10}{'val total':>11}{'policy_top1':>13}{'value_acc':>11}")
    log("-" * 70)
    for row in results:
        v = row["val"]
        log(f"{row['arm']:<10}{row['seed']:>10}{v.get('total', 0):>11.5f}"
            f"{v.get('policy_top1', 0):>13.5f}{v.get('value_acc', 0):>11.5f}")
    if deltas:
        log("")
        log("paired deltas vs baseline "
            "(policy_top1/value_acc higher better; total lower better):")
        log(f"{'arm':<10}{'metric':<14}{'mean':>11}{'min':>11}{'max':>11}{'n':>4}")
        for (arm, metric), values in sorted(deltas.items()):
            log(f"{arm:<10}{metric:<14}{sum(values) / len(values):>+11.5f}"
                f"{min(values):>+11.5f}{max(values):>+11.5f}{len(values):>4}")
        if args.seeds < 3:
            log("")
            log(f"{args.seeds} seed(s): a 3-5 point effect is not resolvable "
                "here. Treat this as a smoke test.")
        log("")
        log("If `shuffled` moves as much as `inputs`, the gain is not the "
            "information, and W3 is not what helped.")
    log("")
    log(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
