"""Game-agnostic AlphaZero loop plumbing shared by board-game adapters."""

from .checkpoint_lifecycle import (
    CheckpointArtifact,
    artifact_for,
    atomic_copy,
    atomic_write_bytes,
    install,
    sha256_file,
)
from .contract import (
    AnchorRequest,
    AnchorResult,
    AssembleRequest,
    GenerateRequest,
    GenerationResult,
    LifecycleAdapter,
    PromotionRequest,
    PromotionResult,
    ReplayResult,
    TrainRequest,
    TrainingResult,
)
from .core import (
    Agent,
    GameAdapter,
    GameJob,
    MatchOutcome,
    play_match,
    run_jobs,
    run_jobs_in_processes,
)
from .elo import EloLedger
from .games_ledger import GamesLedger, count_games, iteration_of_buffer_file
from .hof import HOFEntry, HallOfFame
from .manifest import RunManifest
from .run_controller import ControllerConfig, RunController, RunStore
from .run_log import RunLog
from .schedule import (
    GameSchedule,
    GrowingReplayWindow,
    LinearSchedule,
    ReplayWindow,
    WindowSelection,
)
from .sprt import SPRT, SPRTResult, expected_games_to_decide
from .stats import (
    GateStats,
    GenerationStats,
    IterationStats,
    ModelStats,
    OutcomeStats,
    ReplayStats,
    ResourceMonitor,
    ResourceStats,
    TrainingStats,
    hardware_identity,
    stats_from_row,
    wilson_interval,
)
from .training_control import (
    BootstrapPolicy,
    GateLadder,
    GeneratorMode,
    GeneratorSource,
    GeneratorState,
    PromotionAction,
    TransitionResult,
    decide_transition,
    initial_state,
    select_generator_source,
)

__all__ = [
    "Agent",
    "AnchorRequest",
    "AnchorResult",
    "AssembleRequest",
    "BootstrapPolicy",
    "CheckpointArtifact",
    "ControllerConfig",
    "EloLedger",
    "GameAdapter",
    "GameJob",
    "GameSchedule",
    "GateLadder",
    "GateStats",
    "GamesLedger",
    "GenerateRequest",
    "GenerationResult",
    "GenerationStats",
    "GeneratorMode",
    "GeneratorSource",
    "GeneratorState",
    "GrowingReplayWindow",
    "HOFEntry",
    "HallOfFame",
    "LifecycleAdapter",
    "LinearSchedule",
    "MatchOutcome",
    "ModelStats",
    "OutcomeStats",
    "PromotionAction",
    "PromotionRequest",
    "PromotionResult",
    "ReplayResult",
    "ReplayStats",
    "ReplayWindow",
    "RunController",
    "RunLog",
    "RunManifest",
    "RunStore",
    "ResourceMonitor",
    "ResourceStats",
    "SPRT",
    "SPRTResult",
    "expected_games_to_decide",
    "TrainRequest",
    "TrainingResult",
    "TrainingStats",
    "TransitionResult",
    "WindowSelection",
    "IterationStats",
    "artifact_for",
    "atomic_copy",
    "atomic_write_bytes",
    "count_games",
    "decide_transition",
    "initial_state",
    "iteration_of_buffer_file",
    "install",
    "hardware_identity",
    "play_match",
    "run_jobs",
    "run_jobs_in_processes",
    "select_generator_source",
    "sha256_file",
    "stats_from_row",
    "wilson_interval",
]
