"""Cumulative game counts: the clock every training schedule reads.

Revision 3 of the 7WD cloud plan locked "every schedule expressed in games, not
iterations".  That decision needs a clock, and the clock has one hard
requirement: **resume must recompute it, never restore it**.  A stored schedule
position is a second source of truth that drifts the moment a run is resumed
with a different ``games_per_iteration`` -- which is exactly the situation the
decision exists to prevent (run 03 used 400 games/iteration; a cloud run at
500-800 would silently rescale every iteration-keyed schedule).

So the count is derived from the buffer files themselves.  Those files are
immutable once written -- one per iteration, never rewritten -- which makes a
line count a permanent fact about ``iter_0007.jsonl`` rather than a cached
guess.  The ledger caches counts to avoid re-reading 12 MB per iteration per
iteration, and stores each file's byte size alongside its count so a truncated
or rewritten file invalidates its own cache entry instead of silently reporting
a stale total.

What counts as a game on this clock is a definitional choice, made explicit in
``total_through``: **games generated by the loop**.  A seed corpus is a fixed
prior the run starts with, not progress the run has made, so it does not
advance the schedules.  A6's measured curriculum-bot exhaustion point (~10k
games) is quoted in these units.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import re
from typing import Any

#: ``iter_0007.jsonl`` -> 7.  Anchored so no other file in the buffer directory
#: (``curriculum_seed.jsonl``, autosaves, partial writes) can match.
_ITERATION_FILE = re.compile(r"^iter_(\d{4})\.jsonl$")


def iteration_of_buffer_file(path: Path | str) -> int | None:
    """The iteration a buffer filename encodes, or ``None`` if it is not one."""

    match = _ITERATION_FILE.match(Path(path).name)
    return int(match.group(1)) if match else None


def count_games(path: Path) -> int:
    """Games in a buffer file: one JSON record per non-blank line.

    Counted by lines rather than parsed, because the caller wants a number and
    parsing 12 MB of records to get it is the cost this whole class exists to
    avoid.  Buffers are written by ``_write_records`` one record per line, so
    the two agree by construction; ``test_ledger_matches_parsed_records`` pins
    that agreement so a writer change cannot silently break the clock.
    """

    if not path.exists():
        return 0
    games = 0
    with path.open("rb") as handle:
        for line in handle:
            if line.strip():
                games += 1
    return games


@dataclass(frozen=True, slots=True)
class _Entry:
    games: int
    size_bytes: int


class GamesLedger:
    """Per-iteration and cumulative game counts for a run directory.

    Not a source of truth -- the buffer files are.  This is a memo pad over an
    append-only set of immutable files, and every reader-facing method can be
    satisfied from the files alone if the memo pad is deleted.
    """

    def __init__(self, buffer_dir: str | Path, cache_path: str | Path | None = None):
        self.buffer_dir = Path(buffer_dir)
        self.cache_path = (
            Path(cache_path)
            if cache_path is not None
            else self.buffer_dir.parent / "games_ledger.json"
        )
        self._entries: dict[int, _Entry] = {}
        self._loaded = False

    # -- cache -------------------------------------------------------------

    def _load_cache(self) -> None:
        if self._loaded:
            return
        self._loaded = True
        if not self.cache_path.exists():
            return
        try:
            payload = json.loads(self.cache_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            # A corrupt memo pad is not a run-ending event: everything in it is
            # re-derivable from the buffer files.  Drop it and recount.
            return
        for name, entry in (payload.get("files") or {}).items():
            iteration = iteration_of_buffer_file(name)
            if iteration is None:
                continue
            try:
                self._entries[iteration] = _Entry(
                    games=int(entry["games"]), size_bytes=int(entry["size_bytes"])
                )
            except (KeyError, TypeError, ValueError):
                continue

    def _write_cache(self) -> None:
        payload = {
            "files": {
                f"iter_{iteration:04d}.jsonl": {
                    "games": entry.games,
                    "size_bytes": entry.size_bytes,
                }
                for iteration, entry in sorted(self._entries.items())
            }
        }
        self.cache_path.parent.mkdir(parents=True, exist_ok=True)
        temporary = self.cache_path.with_suffix(".tmp")
        temporary.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        temporary.replace(self.cache_path)

    # -- reads -------------------------------------------------------------

    def path_for(self, iteration: int) -> Path:
        return self.buffer_dir / f"iter_{iteration:04d}.jsonl"

    def games_for(self, iteration: int) -> int:
        """Games generated in one iteration, counting the file if need be.

        A cache entry is trusted only while the file's size still matches the
        size it was counted at.  Immutable files make that check nearly free
        and turn "someone truncated a buffer" from a wrong number into a
        recount.
        """

        self._load_cache()
        path = self.path_for(iteration)
        if not path.exists():
            return 0
        size = path.stat().st_size
        cached = self._entries.get(iteration)
        if cached is not None and cached.size_bytes == size:
            return cached.games
        games = count_games(path)
        self._entries[iteration] = _Entry(games=games, size_bytes=size)
        self._write_cache()
        return games

    def known_iterations(self) -> list[int]:
        """Every iteration with a buffer file on disk, ascending."""

        if not self.buffer_dir.exists():
            return []
        found = [
            iteration
            for path in self.buffer_dir.iterdir()
            if (iteration := iteration_of_buffer_file(path)) is not None
        ]
        return sorted(found)

    def refresh(self) -> None:
        """Count every buffer file now, so later reads are pure cache hits."""

        for iteration in self.known_iterations():
            self.games_for(iteration)

    def total_through(self, iteration: int) -> int:
        """Games generated by iterations 0..``iteration`` inclusive.

        Excludes any seed corpus -- see the module docstring.  Missing files
        contribute zero rather than raising: a run resumed after a failed
        iteration has a gap, and the clock should report the games that exist.
        """

        if iteration < 0:
            return 0
        return sum(
            self.games_for(known)
            for known in self.known_iterations()
            if known <= iteration
        )

    def total_before(self, iteration: int) -> int:
        """Games that existed when ``iteration`` began generating.

        **This is the value schedules read.**  Using games *through* the current
        iteration would make a schedule depend on the games it is currently
        deciding how to generate, which is circular and, worse, differs between
        a fresh run and a resume of the same iteration.
        """

        return self.total_through(iteration - 1)

    def summary(self, iteration: int) -> dict[str, Any]:
        """Clock state for one iteration, for the stats row."""

        return {
            "iteration": iteration,
            "games_before_iteration": self.total_before(iteration),
            "games_this_iteration": self.games_for(iteration),
            "games_through_iteration": self.total_through(iteration),
            "iterations_on_disk": len(self.known_iterations()),
        }
