"""Portable SplitMix64 RNG — the engine's random stream, mirrored bit-for-bit in
Rust (``RUST_PORT_PLAN.md`` M0-B).

Deliberately NOT ``random.Random``: the Mersenne Twister cannot be reproduced in
Rust, so "same seed" would give two different games — and worse, a trajectory
generated by a Rust engine could not be replayed by the Python trainer at all,
because :func:`datagen.replay` rebuilds the deal from the seed.

This is the same stream as ``seven_wonders_duel/portable_rng.py``, which was
written for exactly this reason; ``tests/test_portable_rng.py`` asserts the two
agree bit-for-bit rather than trusting the transcription.  Only the primitives
the *engine* needs are here — the Gumbel/normal/gamma family belongs to search
and arrives with M5 if it is needed.

Every derivation (state transition, uniform, ``randrange``, Fisher-Yates
``shuffle``, ``choice``) is defined so ``welcome_to_rust::rng`` produces an
identical stream from the same seed.
"""

from __future__ import annotations

from bisect import bisect
from itertools import accumulate
from typing import Iterable, Optional, Sequence, TypeVar

_MASK64 = (1 << 64) - 1
_TWO53 = float(1 << 53)
_GAMMA = 0x9E3779B97F4A7C15
_MIX1 = 0xBF58476D1CE4E5B9
_MIX2 = 0x94D049BB133111EB

T = TypeVar("T")


class PortableRng:
    """A reproducible SplitMix64 stream.  Mutable state is a single u64."""

    __slots__ = ("_state",)

    def __init__(self, seed: int):
        self._state = seed & _MASK64

    # ------------------------------------------------------------------
    # State — the whole of it, which is what makes ``copy`` exact and lets
    # the M1 equivalence gate compare the two engines' generators directly.
    # ------------------------------------------------------------------
    @property
    def state(self) -> int:
        return self._state

    @state.setter
    def state(self, value: int) -> None:
        self._state = value & _MASK64

    def clone(self) -> "PortableRng":
        return PortableRng(self._state)

    def getstate(self) -> int:
        """``random.Random``'s spelling, so callers that hold either generator
        do not have to know which one they have.  The state is one integer here
        against 625 words there, which is the whole point."""
        return self._state

    def setstate(self, value: int) -> None:
        self.state = value

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"PortableRng(0x{self._state:016x})"

    # ------------------------------------------------------------------
    # Primitives
    # ------------------------------------------------------------------
    def next_u64(self) -> int:
        self._state = (self._state + _GAMMA) & _MASK64
        z = self._state
        z = ((z ^ (z >> 30)) * _MIX1) & _MASK64
        z = ((z ^ (z >> 27)) * _MIX2) & _MASK64
        return z ^ (z >> 31)

    def next_float(self) -> float:
        """Uniform in [0, 1) from the top 53 bits (exactly representable)."""
        return (self.next_u64() >> 11) / _TWO53

    def randrange(self, n: int) -> int:
        """Integer in [0, n) via modulo (matches Rust ``next_u64() % n``)."""
        if n <= 0:
            raise ValueError("randrange requires n > 0")
        return self.next_u64() % n

    def getrandbits(self, k: int) -> int:
        """Low ``k`` bits (k <= 64).  Used to reseed a determinized copy."""
        if not 0 < k <= 64:
            raise ValueError("getrandbits supports 1..64 bits")
        return self.next_u64() & ((1 << k) - 1)

    def shuffle(self, seq: list) -> None:
        """In-place Fisher-Yates (Durstenfeld), high index to low, so the Rust
        port reproduces the permutation."""
        for i in range(len(seq) - 1, 0, -1):
            j = self.next_u64() % (i + 1)
            seq[i], seq[j] = seq[j], seq[i]

    def choice(self, seq: Sequence[T]) -> T:
        """One element, uniformly.

        ⚠ **Not** ``random.Random.choice``, which draws through ``_randbelow``
        and its rejection loop; this is a plain modulo of one ``next_u64`` so
        that Rust can reproduce it in one line.
        """
        if not seq:
            raise IndexError("cannot choose from an empty sequence")
        return seq[self.next_u64() % len(seq)]

    def choices(
        self,
        population: Sequence[T],
        weights: Optional[Iterable[float]] = None,
        *,
        cum_weights: Optional[Iterable[float]] = None,
        k: int = 1,
    ) -> list[T]:
        """The ``random.Random.choices`` subset search needs, bit-portably.

        Only ``k=1`` is used by MCTS.  The accumulation and ``bisect`` spelling
        intentionally mirrors CPython's implementation; Rust's
        ``weighted_index`` consumes the same one uniform draw.
        """
        if k != 1:
            raise ValueError("PortableRng.choices supports only k=1")
        if not population:
            raise IndexError("cannot choose from an empty population")
        if cum_weights is None:
            if weights is None:
                return [self.choice(population)]
            # Search policies arrive as numpy.float32. Letting itertools keep
            # that scalar type accumulates in f32, while Rust necessarily
            # widens the packed f32 response into its f64 sampler. Cast each
            # term explicitly so wide policies cannot straddle different
            # cumulative thresholds on the same random draw.
            cumulative = list(accumulate(float(weight) for weight in weights))
        else:
            if weights is not None:
                raise TypeError("cannot specify both weights and cum_weights")
            cumulative = [float(weight) for weight in cum_weights]
        if len(cumulative) != len(population):
            raise ValueError("weights and population must be the same length")
        total = float(cumulative[-1])
        if total <= 0.0:
            raise ValueError("total of weights must be greater than zero")
        index = bisect(cumulative, self.next_float() * total, 0, len(population) - 1)
        return [population[index]]


# M0-F: domain separation makes a search's tape independent of scheduler shape.
SEARCH_SEED_DOMAIN: int = 0x5745_4C43_4F4D_4553  # "WELCOMES"


def derive_search_seed(game_seed: int, search_index: int) -> int:
    """The portable tape for one search, independent of other live searches.

    ⚠ **Not** ``game_seed ^ DOMAIN ^ search_index``, which is what this was and
    which collides structurally.  A run draws its game seeds from a contiguous
    block and its search indices from ``0 .. decisions``, so under XOR the
    decision counter lands in the same low bits as the seed: decision ``i`` of
    game ``s`` gets **exactly** the tape decision ``0`` of game ``s ^ i`` gets,
    and every search in a run shares its tape with ~``min(games, decisions)``
    others.  Two searches on one tape draw the same determinization permutations
    *and* -- because ``root_noise`` seeds NumPy from this -- the identical
    Dirichlet vector at equal root width, so the exploration the noise exists to
    buy is silently duplicated across the corpus.

    The derivation is instead one draw of the stream itself: advance
    ``PortableRng(game_seed ^ DOMAIN)`` by ``search_index`` states and take the
    next output.  SplitMix64's state step is ``+GAMMA``, so the skip is O(1),
    the finalizer is a bijection, and a collision needs
    ``Δseed == GAMMA * Δindex (mod 2**64)`` -- unreachable for the seed blocks
    and decision counts a real run uses.
    """
    if search_index < 0:
        raise ValueError("search_index must be non-negative")
    base = ((game_seed ^ SEARCH_SEED_DOMAIN) + _GAMMA * search_index) & _MASK64
    return PortableRng(base).next_u64()
